server:
  address: localhost
  port: 8080

spring:
  application:
    name: exchange

  jpa:
    hibernate.ddl-auto: update
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver

logging:
  level:
    root: INFO
    com.omikheev.testapp.exchange: DEBUG

currencylayer:
  apiKey: b5a70b15b253d9b42690e4a734fb7f9a
  apiUrl: http://apilayer.net/api/
  apiRate: live